til_project/chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_id>/", views.room, name="room"),
]

til_project/chef/urls.py
from django.urls import path
from . import views

app_name = 'chef'

urlpatterns = [
    path('chef_login/', views.chef_login, name="chef_login"),
    path('create-chef-profile/', views.create_chef_profile, name="create_chef_profile"),
    path('chef_home/<int:id>/', views.chef_home, name="chef_home"),
    path('chef_profile/<int:id>/', views.chef_profile, name='chef_profile'),
    path('update_profile/<int:id>/', views.update_profile, name='update_profile'),
    path('availability/<int:id>/', views.chef_availability, name='chef_availability'),
    # path('book/<int:id>/', views.book_availability, name='book_availability'),
    # path('events/<int:id>/', views.availability_events, name='availability_events'),
    path('add_recipe/<int:id>/', views.add_recipe, name='add_recipe'),
    path('display_recipes/<int:id>/', views.display_recipes, name='display_recipes'),
    path('report_customer_form/', views.report_customer_form, name='report_customer_form'),
    path('report_customer/', views.report_customer, name='report_customer'),
    path('recipe/<int:recipe_id>/', views.recipe_profile, name='recipe_profile'),
    path('get_chef_availabilities/<int:id>/', views.get_chef_availabilities, name='get_chef_availabilities'),
    path('chef_chats/<int:id>/', views.chef_chats, name='chef_chats'),
]

til_project/customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'

urlpatterns = [
    path("index/<int:id>/", views.index, name="index"),
    path("report_chef_form/", views.report_chef_form, name="report_chef_form"),
    path("report_chef/", views.report_chef, name="report_chef"),
    path('customer_login/', views.customer_login, name="customer_login"),
    path('create_customer_profile/', views.create_customer_profile, name="create_customer_profile"),
    path('claps/<int:id>', views.clapped, name = 'claps'),
    path('claps/<int:user_id>/<int:recipe_id>/', views.clapped, name='claps'),
    path('liked_chefs/<int:user_id>/', views.liked_chefs, name='liked_chefs'),
    path('favorite_chef/<int:user_id>/<int:chef_id>', views.favorite_chef, name='favorite_chef'),
    path('view-all-recipe/<int:id>', views.view_all_recipes, name= 'view_all_recipe'),
    path('recipe/<int:recipe_id>/<int:customer_id>', views.recipe_view, name='recipe_view'),
    path('chef/<int:customer_id>/<int:chef_id>', views.chef_view, name='chef_view'),

]

til_project/profile_manager/urls.py
from django.urls import include, path
from . import views

app_name = 'profile_manager'

urlpatterns = [
    path('', views.homepage, name="homepage"),
    path('logout/', views.user_logout, name="logout"),
    path('incorrect_user/', views.incorrect_user, name="incorrect_user"),
]

til_project/til_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('profile_manager.urls')),
    path('chef/', include('chef.urls', namespace='chef')),
    path('customer/', include('customer.urls', namespace='customer')),
    path("chat/", include("chat.urls")),
    path('admin/', admin.site.urls),
    path('chatbot/', include('chatbot.urls')),
]

til_project/chef/models.py
from django.db import models
from django.contrib.auth.models import User

class Availability(models.Model):
    date = models.DateField()
    vacancies = models.IntegerField()
    filled_seats = models.IntegerField()

class Chef(models.Model):
    auth_user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    firstname = models.CharField(max_length=225)
    lastname = models.CharField(max_length=225)
    username = models.CharField(max_length=225,unique=True)
    email = models.EmailField(max_length=225)
    password = models.CharField(max_length=225)
    image = models.ImageField(upload_to='images/', default='/images/default_chef.png')
    # availabilities = models.ManyToManyField(Availability, default=None)
    
class Availability(models.Model):
    chef = models.ForeignKey(Chef, on_delete=models.CASCADE, default=None)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    vacancies = models.IntegerField()
    filled_seats = models.IntegerField()
    additional_info = models.TextField()

class Ingredient(models.Model):
    name = models.CharField(max_length=256)
    price = models.DecimalField(default=-1, decimal_places=2, max_digits=6)

class Recipe(models.Model):
    # ID created by default https://docs.djangoproject.com/en/4.2/topics/db/models/
    chef = models.ForeignKey(Chef, on_delete=models.CASCADE, default=None)
    name = models.CharField(max_length=256)
    description = models.TextField()
    claps = models.PositiveIntegerField(default = 0)
    #add ingredients and price
    image = models.ImageField(upload_to='images/', default='/images/default_rec.png')
    total_price = models.DecimalField(default=-1, decimal_places=2, max_digits=6)
    ingredients = models.ManyToManyField(Ingredient)

til_project/chef/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.template import loader
from .create_chef_form import ChefRegistrationForm
from .create_chef_form import RecipeRegistrationForm
from .login_form import LoginForms
from .AvailabilityForm import AvailabilityForm
from django.contrib.auth import login
from django.contrib import messages
from .models import Availability, Recipe, Chef, Ingredient
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.urls import reverse
import json
from django.forms.models import model_to_dict

from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError

from utilities.models import Report

from chat.models import ChatRoom

from .models import Recipe, Chef, Availability, Recipe, Chef, Ingredient
from .models import Availability, Recipe, Chef, Ingredient

from .create_chef_form import ChefRegistrationForm, RecipeRegistrationForm
from .login_form import LoginForms

LOGIN_URL = '/chef/chef_login/'

def chef_login(request):
    if request.method == 'POST':
        form = LoginForms(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            try:
                user = authenticate(request, username=username, password=password)

                if user is None:
                    print(user)
                    messages.error(request, 'invalid username or password. Please try again')
                    return render(request, 'chef_login.html', {'form': form, 'invalid': True})

                login(request, user)
                chef_user = Chef.objects.get(username=username)

                messages.success(request, f'Hello {chef_user.username}! You have been logged in')
                return redirect(reverse('chef:chef_home', args=[chef_user.id]))

            except Chef.DoesNotExist:
                messages.error(request, 'YOU AINT EVEN A USER BRO')
                return render(request, 'chef_login.html', {'form': form, 'invalid': True})
    else:
        form = LoginForms()
    
    return render(request, 'chef_login.html', {'form': form})



def create_chef_profile(request):
    # template = loader.get_template('create_chef_profile.html')
    if request.method == 'POST':
        form = ChefRegistrationForm(request.POST)
        if form.is_valid():
            chef = form.save(commit=False)

            new_user = User(username=chef.username, email=chef.email)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()

            chef.auth_user = new_user
            chef.save()

            print("You have sucessfully created an account")

            login(request, chef.auth_user)
            return redirect(reverse('chef:chef_home', args=[chef.id]))
    else:
        form = ChefRegistrationForm()

    return render(request, 'create_chef_profile.html', {'form': form})
    # return HttpResponse(template.render(None, request))


@login_required(login_url=LOGIN_URL)
def chef_home(request, id):
    user_db = Chef.objects.get(id=id)
    if request.user.is_authenticated and request.user.id != user_db.auth_user.id:
        return redirect(reverse("profile_manager:incorrect_user"))
        
    print(request.user.id)
    print(request.user.is_authenticated)
    try:
        user = Chef.objects.get(id=id)
        recipes = Recipe.objects.filter(chef=user)

        chef_name = user.username.capitalize()
    except Chef.DoesNotExist:
        chef_name = "Guest"  # Provide a default value if the user doesn't exist or if there's an error

    context = {'chef_name': chef_name, 'id': id, 'chef': user, 'recipes': recipes}
    return render(request, 'chef_home.html', context)


@login_required(login_url=LOGIN_URL)
def add_recipe(request, id):
    user_db = Chef.objects.get(id=id)
    if request.user.is_authenticated and request.user.id != user_db.auth_user.id:
        return redirect(reverse("profile_manager:incorrect_user"))
        
    if request.method == "POST":
        form = RecipeRegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            # Create a new recipe
            recipe = form.save(commit=False)
            recipe.chef = Chef.objects.get(id=id)  # Assuming you have user authentication
            recipe.save()

            # Process ingredients
            ingredient_names = request.POST.getlist("ingredient_name")
            ingredient_prices = request.POST.getlist("ingredient_price")
            total_price = 0
            for name, price in zip(ingredient_names, ingredient_prices):
                # Create a new ingredient and associate it with the recipe
                if name and price:
                    ingredient = Ingredient.objects.create(name=name, price=price)
                    recipe.ingredients.add(ingredient)
                    total_price += float(price)
                    
                
            recipe.total_price = total_price + 0.20 * total_price #15% surcharge
            print(recipe.total_price)
            recipe.save()
            form = RecipeRegistrationForm()  # Redirect to a recipe list view
    else:
        form = RecipeRegistrationForm()

    return render(request, "chef_recipe.html", {"form": form, "id": id})


@login_required(login_url=LOGIN_URL)
def chef_profile(request, id):
    user_db = Chef.objects.get(id=id)
    if request.user.is_authenticated and request.user.id != user_db.auth_user.id:
        return redirect(reverse("profile_manager:incorrect_user"))
    
    try:
        user = Chef.objects.get(id=id)
        recipes = Recipe.objects.filter(chef=user)
    except Chef.DoesNotExist:
        # Handle the case where the user doesn't exist
        # You can redirect or display an error message
        pass

    context = {'chef': user, 'recipes': recipes}
    return render(request, 'chef_profile.html', context)


@login_required(login_url=LOGIN_URL)
def display_recipes(request, id):
    user_db = Chef.objects.get(id=id)
    if request.user.is_authenticated and request.user.id != user_db.auth_user.id:
        return redirect(reverse("profile_manager:incorrect_user"))
        
    try:
        user = Chef.objects.get(id=id)
        recipes = Recipe.objects.filter(chef=user)
    except Chef.DoesNotExist:
        # Handle the case where the user doesn't exist
        # You can redirect or display an error message
        pass
    
    context = {'chef': user, 'recipes': recipes.reverse()}
    return render(request, 'all_recipe.html', context)


def recipe_profile(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    chef = recipe.chef
    total_price = sum(ingredient.price for ingredient in recipe.ingredients.all())
    context = {'recipe': recipe, 'chef':chef, 'total_price': total_price}
    return render(request, 'recipe_profile.html', context)


@login_required(login_url=LOGIN_URL)
def update_profile(request, id):
    user_db = Chef.objects.get(id=id)
    if request.user.is_authenticated and request.user.id != user_db.auth_user.id:
        return redirect(reverse("profile_manager:incorrect_user"))
        
    try:
        user = Chef.objects.get(id=id)
    except Chef.DoesNotExist:
        # Handle the case where the user doesn't exist
        # You can redirect or display an error message
        pass

    if request.method == 'POST':
        # Process the form data to update the user's profile
        # You can add the form handling logic here
        # After successfully updating the profile, you can redirect back to the profile page
        user.username = request.POST['username']
        user.firstname = request.POST['firstname']
        user.lastname = request.POST['lastname']
        user.email = request.POST['email']
        user.password = request.POST['password']
        
        # Check if a new image was uploaded
        if 'image' in request.FILES:
            user.image = request.FILES['image']

        # Save the updated user object
        user.save()

        return redirect(reverse('chef:chef_profile', args=[user.id]))

    context = {'user': user}
    return render(request, 'update_profile.html', context)


@login_required(login_url=LOGIN_URL)
def chef_availability(request, id):
    user_db = Chef.objects.get(id=id)
    if request.user.is_authenticated and request.user.id != user_db.auth_user.id:
        return redirect(reverse("profile_manager:incorrect_user"))
        
    chef = get_object_or_404(Chef, id=id)  # Use get_object_or_404 to handle invalid chef IDs
    availabilities = Availability.objects.filter(chef=chef)

def chef_availability(request, id):
    chef = get_object_or_404(Chef, id=id)
    availabilities = Availability.objects.filter(chef=chef)

    events = []
    for availability in availabilities:
        event = {
            'title': f'Availability - {availability.additional_info}',
            'start': str(availability.date) + 'T' + str(availability.start_time),
            'end': str(availability.date) + 'T' + str(availability.end_time),
            'id': availability.id,
        }

        events.append(event)

    events_json = json.dumps(events)

    if request.method == 'POST':
        form = AvailabilityForm(request.POST)
        if form.is_valid():
            availability_data = {
                'date': request.POST['date'],
                'start_time': request.POST['start_time'],
                'end_time': request.POST['end_time'],
                'vacancies': int(request.POST['vacancies']),
                'filled_seats': int(request.POST['filled_seats']),
                'additional_info': request.POST['additional_info'],
            }

til_project/chef/templates/all_recipe.html
<!DOCTYPE html>
<html>

<head>
    <title>Your Recipes</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/global.css?{% now 'U' %}" />
    <link rel="stylesheet" href="/static/recipies.css?{% now 'U' %}" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Zeyada">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <div class="topnav">
        <a>LOGO</a>
        <div class="topnav-right">
            <a href="{% url 'chef:chef_home' chef.id %}">Home</a>
            <a class="active" href="{% url 'chef:display_recipes' chef.id %}"> My Recipies</a>
            <a href="">Bookings</a>
            <div class="dropdown">
                <a style="padding: 0px 0px;"><img src="{{ chef.image.url }}" class="dropbtn"></a>
                <div class="dropdown-content">
                    <a href="{% url 'chef:chef_profile' chef.id %}">Account</a>
                    <a href="{% url 'profile_manager:logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>
                        Logout </a>
                </div>
            </div>
        </div>
    </div>



    <div class="main">

        <h1 style="font-family: Zeyada; font-size: 50px; text-align: center; margin-bottom: 20px; color: #333"
            class="welcome">
            <image src="/static/chef_welcome.png" width="70px"></image> {{ chef.username }}'s Recipes
        </h1>
        <hr>

        <!-- Portfolio Gallery Grid -->
        <div class="row">
            {% for recipe in recipes %}
            <div class="column">
                <div href="{% url 'chef:recipe_profile' recipe.id %}" class="content">
                    <img src="{{ recipe.image.url }}" alt="{{ recipe.name }}" class="recipe-image">
                    <h3 class="recipe-title">{{ recipe.name }}</h3>
                    <p class="recipe-description">{{ recipe.description }}</p>
                </div>
                <a href="{% url 'chef:recipe_profile' recipe.id %}">
                    <div class="middle">
                        <div class="text">View More</div>
                    </div>
                </a>
            </div>
            {% endfor %}
            <div class="columnStay">
                <img src="/static/recipe.png" alt="{{ recipe.name }}" class="recipe-image">
                <br>
                <br>
                <br>
                <div style="max-width: 130px; margin: auto; height: auto; padding-bottom: 30px;">
                   <a href="{% url 'chef:add_recipe' chef.id %}"><button class="button"> Add a Recipe </button></a>
                </div>
            </div>
        </div>
    </div>
    </div>

til_project/chef/templates/chef_chats.html
<!DOCTYPE html>
<html>

<head>
    <title>Home</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/global.css?{% now 'U' %}" />
    <link rel="stylesheet" type="text/css" href="/static/login.css?{% now 'U' %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Zeyada">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

        <div class="topnav">
        <a>LOGO</a>
        <div class="topnav-right">
            <a href="{% url 'chef:chef_home' id=id %}">Home</a>
            <a href="{% url 'chef:display_recipes' id=id %}"> My Recipies</a>
            <a href="{% url 'chef:chef_availability' id=id %}">Bookings</a>
            <a class="active" href="{% url 'chef:chef_chats' id=id %}">Chat</a>
            <div class="dropdown">
                <a style="padding: 0px 0px;"><img src="{{ chef.image.url }}"
                        class="dropbtn"></a>
                <div class="dropdown-content">
                    <a href="{% url 'chef:chef_profile' id=id %}">Account</a>
                    <a href="{% url 'profile_manager:logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>Logout</a>
                </div>
            </div>
        </div>
    </div>


    {% for room in rooms %}
    Chat with customer {{room.customer_id.username}}!
    <button><a href="/chat/{{room.chef_id.id}}_{{room.customer_id.id}}/">Enter Room</a></button>
{% endfor %}

</body>

</html>

til_project/chef/templates/chef_home.html
<!DOCTYPE html>
<html>

<head>
    <title>Home</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/global.css?{% now 'U' %}" />
    <link rel="stylesheet" type="text/css" href="/static/login.css?{% now 'U' %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Zeyada">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
</head>

<body>
    <div class="topnav">
        <a>LOGO</a>
        <div class="topnav-right">
            <a class="active" href="{% url 'chef:chef_home' id=id %}">Home</a>
            <a href="{% url 'chef:display_recipes' id=id %}"> My Recipies</a>
            <a href="{% url 'chef:chef_availability' id=id %}">Bookings</a>
            <a href="{% url 'chef:chef_chats' id=id %}">Chat</a>
            <div class="dropdown">
                <a style="padding: 0px 0px;"><img src="{{ chef.image.url }}"
                        class="dropbtn"></a>
                <div class="dropdown-content">
                    <a href="{% url 'chef:chef_profile' id=id %}">Account</a>
                    <a href="{% url 'profile_manager:logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>Logout</a>
                </div>
            </div>
        </div>
    </div>

    <div>
        <h1 style="font-family: Zeyada; font-size: 50px; text-align: center;" class="welcome">
            <image src="/static/chef_welcome.png" width="70px"></image> Welcome {{ chef_name }}
        </h1>
        <br>
        <br>
    </div>

    <div style="text-align: center; width:500px; margin: auto;">
        <p>Welcome to your Chef Dashboard, the ultimate culinary playground where your gastronomic creativity comes to life! Are you ready to share your scrumptious recipes with the world? Dive into the 'All Recipes' page where your culinary creations take center stage. Here, not only can you feast your eyes on your collection of delectable dishes, but you can also hit the 'Add Recipe' button to sprinkle some more magic into your recipe repertoire. It's like opening a treasure chest of flavors, and you've got the key!</p>
        <br>
        <p>But wait, there's more! Glide over to the 'Bookings' tab right from the top navigation and step into a world where connections are made, and culinary adventures begin. Whether you're looking to showcase your signature dishes or host an exclusive dining experience, this is your moment to shine and create unforgettable memories for food lovers everywhere.</p>
        <br>
        <p>And for the moments in between, your profile picture is your portal to personalization. Give it a click to log in, log out, and manage your account with ease. It's like having a personal culinary assistant right at your fingertips!</p>
        <br>
        <p>Don't forget to check in with your Chat Room, where the conversation is always simmering. Recent messages await, ready to connect you with fellow food enthusiasts and potential clients. It's the perfect space to stir up excitement and cook up new opportunities.</p>
        <br>
        <p>So, what are you waiting for? Your Chef Dashboard is the canvas, and you are the artist. Let's create some culinary magic and spread the joy of cooking, one delicious recipe at a time! Welcome to the hub of flavor, fun, and endless possibilities!</p>
        <br>
        <br>
        <br>
    </div>

</body>

</html>

til_project/chef/templates/chef_login.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <title>Chef Login</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'login.css' %}">
    <link rel="stylesheet" href="/static/global.css?{% now 'U' %}" />
    <link rel="stylesheet" type="text/css" href="/static/login.css?{% now 'U' %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Zeyada">
</head>

<body>

    <div class="topnav">
        <a>LOGO</a>
        <div class="topnav-right">
            <a href="{% url 'profile_manager:homepage' %}">Home</a>
            <a class="active" href="{% url 'chef:chef_login' %}">Chef Login</a>
            <a href="{% url 'customer:customer_login' %}">Customer Login</a>
        </div>
    </div>

    <div class="form-container">
        <br>
        <h1 style="font-family: Zeyada; font-size: 50px;">Chef Login</h1>
        <p>Enter your username and password to login</p>
        <br>
        <form method="POST" class="login">
            {% csrf_token %}

            {% if invalid %}
                Could not find a chef with the given username and password.

                {% for error in form.non_field_errors %}
                    <p class="error">{{ error }}</p>
                {% endfor %}
            {% endif %}

            <label for="{{ form.username.id_for_label }}" class="form-label">Username:</label>
            {{ form.username }}

            <label for="{{ form.password.id_for_label }}" class="form-label">Password:</label>
            {{ form.password }}

            <button type="submit" class="submit-button">Login</button>
        </form>
    </div>


    <div class="center">
        <p>if you don't have an account: &nbsp;&nbsp;&nbsp;</p>
        <button><a href="{% url 'chef:create_chef_profile' %}">Create Account</a></button>
    </div>

</body>

</html>

til_project/chef/templates/chef_profile.html
<!DOCTYPE html>
<html>

<head>
    <title>Account</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/global.css?{% now 'U' %}" />
    <link rel="stylesheet" type="text/css" href="/static/login.css?{% now 'U' %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Zeyada">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body style="background-color: #333;">

    <div class="topnav">
        <a>LOGO</a>
        <div class="topnav-right">
            <a href="{% url 'chef:chef_home' chef.id %}">Home</a>
            <a href="{% url 'chef:display_recipes' chef.id %}"> My Recipies</a>
            <a href="">Bookings</a>
            <div class="dropdown">
                <a style="padding: 0px 0px;"><img src="{{ chef.image.url }}"
                        class="dropbtn"></a>
                <div class="dropdown-content">
                    <a class="active" href="{% url 'chef:chef_profile' chef.id %}">Account</a>
                    <a href="{% url 'profile_manager:logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout </a>
                </div>
            </div>
        </div>
    </div>

    <h1 style="font-family: Zeyada; font-size: 50px; text-align: center; margin-bottom: 20px; color: #fff8dc" class="welcome">
        <image src="/static/chef_welcome.png" width="70px"></image> {{ chef.username }}'s profile
    </h1>

    <div style="max-width: 150px; margin: auto; text-align: center; margin-bottom: 50px;">
        <a href="{% url 'chef:update_profile' chef.id %}"><button> Edit Profile </button></a>
    </div>

    <div class="profileContainer">
        <div class="profile">
            <div class="profileColumn">
                <h2 class="profileContent"> Username:</h2>
                <h2 class="profileContent"> First Name:</h2>
                <h2 class="profileContent"> Last Name:</h2>
                <h2 class="profileContent"> Email:</h2>
                <h2 class="profileContent"> Password:</h2>
                <h2 class="profileContent"> Profile Picture:</h2>
            </div>

            <div class="profileColumn">
                <h2 class="profileInfo"> {{ chef.username }} </h2>
                <h2 class="profileInfo"> {{ chef.firstname }} </h2>
                <h2 class="profileInfo"> {{ chef.lastname }} </h2>
                <h2 class="profileInfo"> {{ chef.email }} </h2>
                <h2 class="profileInfo"> ●●●●●●●● </h2>
                <h2 class="profileContent"><image width="100px" src="{{ chef.image.url }}"></image></h2>
            </div>
            <br>
        </div>
    </div>

</body>

</html>

til_project/chef/templates/create_chef_profile.html
<!DOCTYPE html>
<html>

<head>
    <title>Chef Login</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/global.css?{% now 'U' %}" />
    <link rel="stylesheet" href="/static/login.css?{% now 'U' %}" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Zeyada">
</head>

<body>

    <div class="topnav">
        <a>LOGO</a>
        <div class="topnav-right">
            <a class="active" href="{% url 'profile_manager:homepage' %}">Home</a>
            <a href="{% url 'chef:chef_login' %}">Chef Login</a>
            <a href="{% url 'customer:customer_login' %}">Customer Login</a>
        </div>
    </div>


    <div class="form-container">
        <br>
        <h1 style="font-family: Zeyada; font-size: 50px;">Create Chef Account</h1>
        <p>Fill in the following form to create a chef profile!</p>
        <br>
        <form method="post" class="create_chef_profile">
            {% csrf_token %}
            {{ form.non_field_errors }}

            <label for="{{ form.firstname.id_for_label }}" class="form-label">First Name:</label>
            {{ form.firstname }}

            <label for="{{ form.lastname.id_for_label }}" class="form-label">Last Name:</label>
            {{ form.lastname }}

            <label for="{{ form.username.id_for_label }}" class="form-label">Username:</label>
            {{ form.username }}

            <label for="{{ form.email.id_for_label }}" class="form-label">Email:</label>
            {{ form.email }}

            <label for="{{ form.password.id_for_label }}" class="form-label">Password:</label>
            {{ form.password }}
            <br><br>
            <button type="submit" class="submit-button">Submit</button>
        </form>
    </div>


    <div class="center">
        <p>if you already have an account: &nbsp;&nbsp;&nbsp;</p>
        <button><a href="{% url 'chef:chef_login' %}">Login</a></button>
    </div>


</body>

</html>